
services:

  frontend:
    image: registry.digitalocean.com/myregistrytayyab/frontend:1.0.0
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./.docker/dev/frontend/Dockerfile
    volumes:
      - ./src:/var/www
    
    restart: unless-stopped
    working_dir: /var/www
    networks:
      - dockerphp
    
    ports:
      - "8023:80"

  backend:
    image: registry.digitalocean.com/myregistrytayyab/backend:1.0.0
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./.docker/dev/backend/Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - dockerphp
      


networks:
  dockerphp:
    driver: bridge



  